app = "marlee-gerard-portfolio"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"   # <-- forces Docker, skips Node buildpack

[[services]]
  protocol = "tcp"
  internal_port = 80

  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls","http"]
    port = 443